/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JButton;

/**
 *
 * @author Familia prieto
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    
    private Modelo modelo;
    private ControlVtnPrincipal ctrlVtnPrincipal;
    
    public VentanaPrincipal(Modelo aThis) {
        initComponents();
        setSize(1035,750);
        setResizable(false);
        setLocationRelativeTo(null);
        modelo = aThis;
        capturarEventos();
    }

    public Modelo getModelo() {
        if(modelo == null){
            modelo= new Modelo();
        }      
        return modelo;
    }

    public ControlVtnPrincipal getCtrlVtnPrincipal() {
        if(ctrlVtnPrincipal== null){
            ctrlVtnPrincipal= new ControlVtnPrincipal(this);
        }
        return ctrlVtnPrincipal;
    }

    public JButton getBtnLessPay() {
        return btnLessPay;
    }

    public JButton getBtnConferencias() {
        return btnConferencias;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public JButton getBtnTerapias() {
        return btnTerapias;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConferencias = new javax.swing.JButton();
        btnTerapias = new javax.swing.JButton();
        btnLessPay = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Aget SA");
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Aget SA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 130, 60);

        btnConferencias.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnConferencias.setForeground(new java.awt.Color(204, 51, 0));
        btnConferencias.setText("Conferencias");
        btnConferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConferenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConferencias);
        btnConferencias.setBounds(530, 30, 140, 20);

        btnTerapias.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnTerapias.setForeground(new java.awt.Color(204, 51, 0));
        btnTerapias.setText("Terapias");
        getContentPane().add(btnTerapias);
        btnTerapias.setBounds(380, 30, 140, 20);

        btnLessPay.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnLessPay.setForeground(new java.awt.Color(204, 102, 0));
        btnLessPay.setText("LessPay");
        getContentPane().add(btnLessPay);
        btnLessPay.setBounds(740, 30, 140, 20);

        btnSalir.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(730, 60, 70, 20);

        btnLogin.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 102, 102));
        btnLogin.setText("Login");
        getContentPane().add(btnLogin);
        btnLogin.setBounds(810, 60, 80, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoAget_icon.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 0, 90, 90);

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agetBanner.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 70, 560, 350);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(690, 410, 330, 300);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 410, 330, 300);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 410, 330, 300);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lesspayBanner_2.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(680, 90, 244, 310);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1030, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConferenciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferencias;
    private javax.swing.JButton btnLessPay;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerapias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void capturarEventos() {
        btnSalir.addActionListener(getCtrlVtnPrincipal());
        btnLessPay.addActionListener(getCtrlVtnPrincipal());
        btnConferencias.addActionListener(getCtrlVtnPrincipal());
        btnLogin.addActionListener(getCtrlVtnPrincipal());
        btnTerapias.addActionListener(getCtrlVtnPrincipal());
    }
}
