/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Ventanas;

import Agenda.ControlVentanaTerapias;
import Presentacion.Modelo;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Pili
 */
public class VentanaTerapias extends javax.swing.JFrame {

    private Modelo modelo;
    private ControlVentanaTerapias ctrlVentanaTerapias;

    public VentanaTerapias(Modelo a) {
        initComponents();
        setSize(670, 450);
        setResizable(false);
        setLocationRelativeTo(null);
        modelo = a;
        capturarEventos();
    }

    @SuppressWarnings("unchecked")

    public Modelo getModelo() {
        if (modelo == null) {
            modelo = new Modelo();
        }
        return modelo;
    }

    public ControlVentanaTerapias getCtrlVtnTerapias() {
        if (ctrlVentanaTerapias == null) {
            ctrlVentanaTerapias = new ControlVentanaTerapias(this);
        }
        return ctrlVentanaTerapias;
    }

    public void setCtrlVentanaTerapias(ControlVentanaTerapias ctrlVentanaTerapias) {
        this.ctrlVentanaTerapias = ctrlVentanaTerapias;
    }
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jCedula = new javax.swing.JTextField();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        jComboBoxFecha = new javax.swing.JComboBox<>();
        jComboBoxHora = new javax.swing.JComboBox<>();
        txtTerapeuta = new javax.swing.JTextField();
        btnSolicitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Terapias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setText("Agenda tu cita en línea");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel4.setText("Cédula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel5.setText("Especialidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel6.setText("Fecha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel7.setText("Hora");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel8.setText("Terapeuta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 153, -1));

        jCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 153, -1));

        jComboBoxEspecialidad.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jComboBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la especialidad", "Compras compulsivas", "Adicción a las apuestas" }));
        jComboBoxEspecialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEspecialidadItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jComboBoxFecha.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jComboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la fecha" }));
        getContentPane().add(jComboBoxFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jComboBoxHora.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jComboBoxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la hora" }));
        getContentPane().add(jComboBoxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));
        getContentPane().add(txtTerapeuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 148, -1));

        btnSolicitar.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnSolicitar.setForeground(new java.awt.Color(0, 102, 102));
        btnSolicitar.setText("Solicitar Cita");
        getContentPane().add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 20));

        btnSalir.setBackground(new java.awt.Color(0, 51, 51));
        btnSalir.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Volver");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, 20));

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 670, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreActionPerformed

    private void jCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCedulaActionPerformed

    private void jComboBoxEspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEspecialidadItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.jComboBoxEspecialidad.getSelectedIndex() > 0) {
                this.jComboBoxFecha.setModel(new DefaultComboBoxModel(this.getFechas(this.jComboBoxEspecialidad.getSelectedItem().toString())));
                this.jComboBoxHora.setModel(new DefaultComboBoxModel(this.getHoras(this.jComboBoxEspecialidad.getSelectedItem().toString())));

                if (this.jComboBoxEspecialidad.getSelectedIndex() == 1) {
                    getTxtTerapeuta().setText("Viviana Prieto");
                } else if (this.jComboBoxEspecialidad.getSelectedIndex() == 2) {
                    getTxtTerapeuta().setText("Diego Lugo");
                }
            }
        }
    }//GEN-LAST:event_jComboBoxEspecialidadItemStateChanged

    public String[] getFechas(String especialidad) {
        String[] fechas = new String[5];
        if (especialidad.equalsIgnoreCase("Compras Compulsivas")) {
            fechas[0] = "08/12/2016";
            fechas[1] = "18/12/2016";
            fechas[2] = "28/12/2016";
            fechas[3] = "08/01/2017";
            fechas[4] = "18/01/2017";
        }

        if (especialidad.equalsIgnoreCase("Adicción a las Apuestas")) {
            fechas[0] = "15/12/2016";
            fechas[1] = "20/12/2016";
            fechas[2] = "25/12/2016";
            fechas[3] = "30/12/2016";
            fechas[4] = "04/01/2017";
        }
        return fechas;
    }

    public String[] getHoras(String especialidad) {
        String[] horas = new String[5];
        if (especialidad.equalsIgnoreCase("Compras Compulsivas")) {
            horas[0] = "8:00 am";
            horas[1] = "10:00 am";
            horas[2] = "12:00 m";
            horas[3] = "2:00 pm";
            horas[4] = "4:00 pm";
        }

        if (especialidad.equalsIgnoreCase("Adicción a las Apuestas")) {
            horas[0] = "9:00 am";
            horas[1] = "10:00 am";
            horas[2] = "11:00 m";
            horas[3] = "2:00 pm";
            horas[4] = "5:00 pm";
        }
        return horas;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JTextField jCedula;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JComboBox<String> jComboBoxFecha;
    private javax.swing.JComboBox<String> jComboBoxHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombre;
    private javax.swing.JTextField txtTerapeuta;
    // End of variables declaration//GEN-END:variables

    public JTextField getjNombre() {
        return jNombre;
    }

    public void setjNombre(JTextField jNombre) {
        this.jNombre = jNombre;
    }

    public JTextField getTxtTerapeuta() {
        return txtTerapeuta;
    }

    public void setTxtTerapeuta(JTextField txtTerapeuta) {
        this.txtTerapeuta = txtTerapeuta;
    }

    public JTextField getjCedula() {
        return jCedula;
    }

    public void setjCedula(JTextField jCedula) {
        this.jCedula = jCedula;
    }

    public JButton getBtnSolicitar() {
        return btnSolicitar;
    }

    public void setBtnSolicitar(JButton btnSolicitar) {
        this.btnSolicitar = btnSolicitar;
    }

    public JComboBox<String> getjComboBoxEspecialidad() {
        return jComboBoxEspecialidad;
    }

    public void setjComboBoxEspecialidad(JComboBox<String> jComboBoxEspecialidad) {
        this.jComboBoxEspecialidad = jComboBoxEspecialidad;
    }

    public JComboBox<String> getjComboBoxFecha() {
        return jComboBoxFecha;
    }

    public void setjComboBoxFecha(JComboBox<String> jComboBoxFecha) {
        this.jComboBoxFecha = jComboBoxFecha;
    }

    public JComboBox<String> getjComboBoxHora() {
        return jComboBoxHora;
    }

    public void setjComboBoxHora(JComboBox<String> jComboBoxHora) {
        this.jComboBoxHora = jComboBoxHora;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    private void capturarEventos() {
        btnSalir.addActionListener(getCtrlVtnTerapias());
        btnSolicitar.addActionListener(getCtrlVtnTerapias());
    }
}
