/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Ventanas;

import Presentacion.Controladores.controlVentanaIngreso;
import Presentacion.Modelo;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class ventanaIngreso extends javax.swing.JFrame {
    
    private Modelo modelo;
    private controlVentanaIngreso controlVentanaIngreso;
    
    public ventanaIngreso(Modelo a) {
        initComponents();
        setSize(400,390);
        setResizable(false);
        setLocationRelativeTo(null);
        modelo = a;
        capturarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 20, 150, 50);

        jLabel3.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 86, 39);

        jLabel4.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 130, 33);

        txtUsuario.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(180, 120, 170, 30);

        btnAceptar.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Checked-24.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(120, 200, 150, 30);

        btnSalir.setBackground(new java.awt.Color(0, 51, 51));
        btnSalir.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir);
        btnSalir.setBounds(210, 280, 120, 30);

        jLabel7.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        jLabel7.setText("Cédula");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 80, 86, 39);

        txtId.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        txtId.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtId);
        txtId.setBounds(180, 80, 170, 30);

        btnRegistrarse.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(0, 102, 102));
        btnRegistrarse.setText("Regístrate");
        getContentPane().add(btnRegistrarse);
        btnRegistrarse.setBounds(60, 280, 100, 27);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("¿Aún no tienes cuenta?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 170, 40);

        txtContrasenia.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtContrasenia);
        txtContrasenia.setBounds(180, 160, 170, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -120, 400, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public Modelo getModelo() {
        if(modelo == null){
        modelo = new Modelo();
        }
        return modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    public controlVentanaIngreso getControlVentanaIngreso() {
        if (controlVentanaIngreso== null){
        controlVentanaIngreso = new controlVentanaIngreso(this);
        }
        return controlVentanaIngreso;
    }

    public void setControlVentanaIngreso(controlVentanaIngreso controlVentanaIngreso) {
        this.controlVentanaIngreso = controlVentanaIngreso;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JTextField getTxtContrasenia() {
        return txtContrasenia;
    }

    public void setTxtContrasenia(JPasswordField txtContrasenia) {
        this.txtContrasenia = txtContrasenia;
    }


    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JButton getBtnRegistrarse() {
        return btnRegistrarse;
    }

    public void setBtnRegistrarse(JButton btnRegistrarse) {
        this.btnRegistrarse = btnRegistrarse;
    }
      
    private void capturarEventos() {
        btnAceptar.addActionListener(getControlVentanaIngreso());
        btnSalir.addActionListener(getControlVentanaIngreso());
        btnRegistrarse.addActionListener(getControlVentanaIngreso());
    }
}
